eugenyk/hpcourse

leti/0303/mav/mdp/.gitignore, leti/0303/mav/mdp/App.config, leti/0303/mav/mdp/HopscotchHashMap.cs, leti/0303/mav/mdp/HopscotchHashMap.csproj, leti/0303/mav/mdp/HopscotchHashMap.sln, leti/0303/mav/mdp/LICENSE, leti/0303/mav/mdp/MapBenchmarks.cs, leti/0303/mav/mdp/Program.cs, leti/0303/mav/mdp/Properties/AssemblyInfo.cs, leti/0303/mav/mdp/README.md, leti/0303/mav/mdp/packages.config
Участники проекта: Морозов Алексей, Москвина Любовь, Данченков Вадим, Фёдоров Всеволод.
В приложении к исходной статье (2008) допущена ошибка в методе `find_closer_free_bucket`, строка 29:
`*free_distance -= free_dist;`
следует заменить на
`*free_distance -= (HOP_RANGE - 1) - move_free_distance`
Для тестирования корректности и сравнения производительности со стандартной реализацией `ConcurrentDictionary<K, V>` используется библиотека BenchmarkDotNet.
=> [Ready] MDP "Hopscotch Hash Map"

leti/0303/ovv/1/client/client.py, leti/0303/ovv/1/server/src/ServerExecutor.java, leti/0303/ovv/1/server/src/ServerExecutorRequest.java, leti/0303/ovv/1/server/src/ServerReceiver.java, leti/0303/ovv/1/server/src/ServerResponder.java
- Исправил WritePendingException и StackOverflow с помощью использования очереди отправки, в данной реализации она общая, лучше использовать персональную очередь для каждого получателя;
- Логика метода completed у ServerReceiver такова: пишем в messageStream полученные данные, если получили больше 4 байт и там есть целое сообщение, то обрабатываем его, при это все данные после сообщения оставляем в messageStream.
=> Исправленная лабораторная работа (Осипов В.В 0303)

aptu/604_16/gsa/tbb_flow_graph/.gitignore, aptu/604_16/gsa/tbb_flow_graph/main.cpp, aptu/604_16/gsa/tbb_flow_graph/tbb_flow_graph.pro
=> Lab1. Golovanov Sergey. Ready

leti/1381/tka/src/Data.cpp, leti/1381/tka/src/Data.h, leti/1381/tka/src/Graph.cpp, leti/1381/tka/src/picture.cpp, leti/1381/tka/src/picture.h
=> add LR1. Tarasov Konstantin 1381 LETI

leti/1381/gap/gap_1/src/Arg_parser.cpp, leti/1381/gap/gap_1/src/Arg_parser.h, leti/1381/gap/gap_1/src/FlowGraphImage.cpp, leti/1381/gap/gap_1/src/Image.cpp, leti/1381/gap/gap_1/src/Image.h
Параметры приложения:
- “-b 123”: интересующее значение яркости
- “-l 5”: предел одновременно обрабатываемых приложением изображений
-  “-n 10”: Количество изображений 
- “-f log.txt”: имя файла журнала яркостей
=> Lab1. Greyner Andrey. 1381. For check

aptu/604_16/aia/1/Makefile, aptu/604_16/aia/1/src/input_parser.h, aptu/604_16/aia/1/src/main.cpp, aptu/604_16/aia/1/src/random_image.cpp, aptu/604_16/aia/1/src/random_image.h
=> Lab1. Abramov Ivan. Ready

aptu/604_16/serebro/1/CMakeLists.txt, aptu/604_16/serebro/1/main.cpp
=> Lab 1. Andrei Serebro. Ready.

FlowGraph/Makefile, FlowGraph/src/main.cpp
=> Flow graph

.gitmodules
Сделал в отдельном репозитории, добавляю как субмодуль. Если надо могу залить прямо сюда.
=> Lab 2. Dmitry Zykov, 1303. Ready.

leti/1304/dea/1/CMakeLists.txt, leti/1304/dea/1/image.cpp, leti/1304/dea/1/image.h, leti/1304/dea/1/main.cpp, leti/1304/dea/1/pixel.h, leti/1304/dea/1/program_settings.cpp, leti/1304/dea/1/program_settings.h
Demin A.D. gr.1304. Ready to check
=> Demin A.D. gr.1304. Ready to check

aptu/604_16/mordberg/.gitignore, aptu/604_16/mordberg/1/CMakeLists.txt, aptu/604_16/mordberg/1/cmake/FindTBB.cmake, aptu/604_16/mordberg/1/src/Image.cpp, aptu/604_16/mordberg/1/src/Image.h, aptu/604_16/mordberg/1/src/ImageProcessor.cpp, aptu/604_16/mordberg/1/src/ImageProcessor.h, aptu/604_16/mordberg/1/src/main.cpp
Здравствуйте!
Посмотрите, пожалуйста мою лабораторную. Две другие (которые на opencl) я добавил в отдельный репозиторий: https://github.com/AntonGitName/au-parallel-computing.
=> [SPbAU] Flow Graph task. Anton Mordberg

aptu/604_16/sdk/1/Makefile, aptu/604_16/sdk/1/src/ArgumentsParser.cpp, aptu/604_16/sdk/1/src/ArgumentsParser.h, aptu/604_16/sdk/1/src/FlowGraphBuilder.cpp, aptu/604_16/sdk/1/src/FlowGraphBuilder.h, aptu/604_16/sdk/1/src/Generator.cpp, aptu/604_16/sdk/1/src/Generator.h, aptu/604_16/sdk/1/src/ParseException.h, aptu/604_16/sdk/1/src/main.cpp, aptu/604_16/sdk/1/src/typedefs.h
=> Savvinov Dmitry. HA1 TBB Flow Graph. For check.

leti/1303/nk/1/CMakeLists.txt, leti/1303/nk/1/main.cpp
To build use CMakeLists.txt
To run use -help option.
Example:
main -help
main -n 5000 -m 5000 -c 2 -l 5 -b 143 -f log.txt
=> Lab1. For check.

leti/1303/bl/lab1/CMakeLists.txt, leti/1303/bl/lab1/main.cpp, leti/1303/bli/1/CMakeLists.txt, leti/1303/bli/1/main.cpp
Lab #1. Leti. Group 1303. Budaeva Liubov.
=> Lab #1. Group 1303. Budaeva Liubov.

aptu/302_17/nikonov/3/CMakeLists.txt, aptu/302_17/nikonov/3/Options.cpp, aptu/302_17/nikonov/3/Options.h, aptu/302_17/nikonov/3/Picture.cpp, aptu/302_17/nikonov/3/Picture.h, aptu/302_17/nikonov/3/main.cpp
=> Nikonov, 302, task #3

aptu/302_17/rebryk/lockfreeset/lockfreeset.iml, aptu/302_17/rebryk/lockfreeset/pom.xml, aptu/302_17/rebryk/lockfreeset/src/main/java/lockfreeset/LockFreeSet.java, aptu/302_17/rebryk/lockfreeset/src/main/java/lockfreeset/Set.java, aptu/302_17/rebryk/lockfreeset/src/test/java/lockfreeset/MultiThreadTest.java, aptu/302_17/rebryk/lockfreeset/src/test/java/lockfreeset/SingleThreadTest.java
Implemented lock-free linked list
=> Rebryk Yurii, 302, Hw #2

aptu/604_17/myrov/1/makefile, aptu/604_17/myrov/1/src/main.cpp, aptu/604_17/myrov/1/test_sum.py
убрал лишние изменения, теперь все должно быть нормально.
Запутался что-то с гитом немного.
=> Myrov lab 1.

leti/2381/chulanov/1/main.cpp, leti/2381/chulanov/2/lab2/LockFreeSet.java, leti/2381/chulanov/2/lab2/LockFreeSetImpl.java, leti/2381/chulanov/2/lab2/Main.java
Chulanov Andrey, leti, 2381
Added 1st lab.
=> Chulanov, LETI, added the 2nd lab

leti/2381/zhangirov/1/lab1.cpp, leti/2381/zhangirov/2/LockFreeSet.java, leti/2381/zhangirov/2/LockFreeSetImpl.java
=> LETI 2381 Zhangirov T.R. Lab1 & Lab2

leti/2304/likhachev/lb1/CMakeLissts.txt, leti/2304/likhachev/lb1/main.cpp, leti/2304/likhachev/lb2/LockFreeSet.java, leti/2304/likhachev/lb2/LockFreeSetImpl.java, leti/2304/likhachev/lb2/Main.java
готовые 1 и 2 лабы, продолжаем мучить мдп
=> leti 2304, Likhachev lb1-2

leti/2381/Lapkina/laba_1/CMakeLists.txt, leti/2381/Lapkina/laba_1/main.cpp, leti/2381/Lapkina/laba_2/src/main/java/LockFreeContainer.java, leti/2381/Lapkina/laba_2/src/main/java/LockFreeSet.java, leti/2381/Lapkina/laba_2/src/main/java/Main.java, leti/2381/Lapkina/laba_2/src/main/java/Node.java, leti/2381/Lapkina/laba_2/src/main/java/Window.java, leti/2381/Lapkina/laba_2/src/test/java/ContainerOperationsTests.java
=> LETI_2381_Lapkina_A_S

leti/2381/budchan/1/main.cpp, leti/2381/budchan/2/LockFreeContainer.iml, leti/2381/budchan/2/src/com/lockfreeset/LockFreeSet.java, leti/2381/budchan/2/src/com/lockfreeset/LockFreeSetImpl.java, leti/2381/budchan/2/src/com/lockfreeset/Main.java
Added first lab - producer-consumer with pthread API.
=> LETI, 2381, Budchan D.S, Lab1, Lab2

aptu/604_17/chernigovskaya/1/main.cpp, aptu/604_17/chernigovskaya/2/LockFreeSetImpl.java
=> Черниговская Мария, BI

aptu/302_18/bogomolov/01/CMakeLists.txt, aptu/302_18/bogomolov/01/main.cpp
=> АУ, Богомолов Егор, 01, pthread api

.gitignore, aptu/302_18/sazanovich/pthread_api/CMakeLists.txt, aptu/302_18/sazanovich/pthread_api/main.cpp
Первое домашнее задание.
Там еще хотелось бы не вносить каждому, кто использует CLion, cmake-build-debug/, cmake-build-release/ в личный .gitignore, а один раз в вам корневой. Если вы не против, то я тут занес уже. (:
=> АУ, Никита Сазанович, pthread-api

aptu/302_18/zhidkov/1/solve.cpp
Только вчера увидел, что надо сдавать через гитхаб.
Если был какой-то дедлайн, то я отсылал этот .cpp довольно давно Вам на почту
=> AU, Nikolay Zhidkov, Lab 01

aptu/302_18/lobanov/01/CMakeLists.txt, aptu/302_18/lobanov/01/task.cpp
Нигде не нашёл информацию о дедлайнах, поэтому всё же попытаюсь. Лучше поздно, чем никогда.
=> AU, Artyom Lobanov, Lab 1

aptu/302_18/fedorova/002/build.gradle, aptu/302_18/fedorova/002/gradlew, aptu/302_18/fedorova/002/gradlew.bat, aptu/302_18/fedorova/002/settings.gradle, aptu/302_18/fedorova/002/src/main/java/LockFreeSet.java, aptu/302_18/fedorova/002/src/main/java/LockFreeSetImpl.java, aptu/302_18/fedorova/002/src/test/java/LockFreeSetImplTest.java
=> AU, Anna Fedorova, Lab 02

aptu/302_18/koshchenko/01/main.cpp, aptu/302_18/koshchenko/01/makefile
Первое дз.
Из-за проблем с виртуалкой это все дело тестилось в онлайн компиляторах, но по идее проблем не должно быть.
=> АУ, Кощенко Катя, Lab01

leti/3304/bakaev/1/CMakeLists.txt, leti/3304/bakaev/1/main.cpp
=> 1 Бакаев Илья ЛЭТИ [3304]

hse/BPM161/pravilov/1/CMakeLists.txt, hse/BPM161/pravilov/1/main.cpp
Проверил helgrind'ом, ошибок не выдает.
=> hw01, Pravilov, HSE

hse/BPM161/abramov/1/CMakeLists.txt, hse/BPM161/abramov/1/src/main.cpp, hse/BPM161/abramov/1/test.sh
It's 1 commit because I've been doing it in other repository.
=> HW#1, HSE, Abramov

hse/BPM161/alferov/1/CMakeLists.txt, hse/BPM161/alferov/1/main.cpp
Summing up integers in stdin using producer/consumer idiom
=> HW#1, HSE, Alferov

hse/BPM161/nedikov/2/build.gradle, hse/BPM161/nedikov/2/gradle/wrapper/gradle-wrapper.properties, hse/BPM161/nedikov/2/gradlew, hse/BPM161/nedikov/2/gradlew.bat, hse/BPM161/nedikov/2/settings.gradle, hse/BPM161/nedikov/2/src/jcstress/java/pack/AddOrderTest.java, hse/BPM161/nedikov/2/src/jcstress/java/pack/AddRemoveTest.java, hse/BPM161/nedikov/2/src/jcstress/java/pack/ConcurrentAddTest.java, hse/BPM161/nedikov/2/src/jcstress/java/pack/RemoveTest.java, hse/BPM161/nedikov/2/src/main/java/pack/ILockFreeSet.java, hse/BPM161/nedikov/2/src/main/java/pack/LockFreeSet.java, hse/BPM161/nedikov/2/src/test/java/pack/LockFreeSetTest.java, hse/BPM161/nedikov/2/src/test/java/pack/LockFreeSetTestLinCheck.java
Я не очень старался над красотой кода, стиля и тестов, но вроде должно быть не сложно и понятно
=> HW#2, HSE, Nedikov
